#!/usr/bin/bash
echo "CLONE-------------------"
git clone https://github.com/sipcapture/homer7-docker
echo "GO TO DOCKER CONFIGS------------------"
cd homer7-docker/heplify-server/hom7-prom-all
echo "COMPOSE----------------------"
sudo docker-compose up -d
