#!/usr/bin/bash
clear && echo "UPDATING..."
sudo apt-get update && sudo apt-get upgrade -y
echo "INSTALL BASE..."
sudo apt-get install git docker docker-compose golang npm

cd $HOME && mkdir qxip && cd qxip

